export { default as About } from './About'
export { default as Home } from './Home'
export { default as Contact } from './Contact'
export { default as BikeKitchen } from './BikeKitchen'
export { default as Events } from './Events'
