export { default as About } from './about'
export { default as Home } from './home'
export { default as Contact } from './contact'
export { default as BikeKitchen } from './bikekitchen'
export { default as Events } from './events'
